server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/coordinator/ {
        rewrite ^/api/coordinator/(.*) /$1 break;
        proxy_pass http://coordinator:3000;
    }

    location /api/pool/ {
        rewrite ^/api/pool/(.*) /$1 break;
        proxy_pass http://pool:3001;
    }
}
