apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: infra-pool
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "infra"
        effect: "NoSchedule"
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
