# Default values for blockchain Helm chart
replicaCount: 3

image:
  repository: gcr.io/proyectosdypp2026/pilar2-blockchain
  pullPolicy: IfNotPresent
  tag: "latest"

frontend:
  image:
    repository: gcr.io/proyectosdypp2026/pilar2-frontend
    tag: "latest"

service:
  type: ClusterIP
  port: 3000

rabbitmq:
  url: "amqps://guest:guest@rabbitmq:5671"

redis:
  url: "redis://redis:6379"

difficulty: "0000"

pool:
  url: "http://pool:3001"
  blockThreshold: 5

rabbitmq:
  url: "amqps://guest:guest@rabbitmq:5671"
  dashboardUrl: "http://34.10.131.154:15672"
  # ⚠️ Si Rabbitmq cambia de IP por recrear el cluster, actualizar dashboardUrl acá y hacer helm upgrade

logLevel: "info"

worker:
  replicaCount: 3
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 70

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
