apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockchain.fullname" . }}-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: app-pool
      containers:
        - name: coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: SERVICE
              value: "coordinator"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
