apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain.fullname" . }}-frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
