apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain.fullname" . }}-worker-service
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
