apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockchain.fullname" . }}-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool
  template:
    metadata:
      labels:
        app: pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: app-pool
      containers:
        - name: pool
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: SERVICE
              value: "pool"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: BLOCK_THRESHOLD
              value: {{ .Values.pool.blockThreshold | default 5 | quote }}
            - name: DIFFICULTY
              value: {{ .Values.difficulty | default "0000" | quote }}
          ports:
            - containerPort: 3001
          livenessProbe:
            tcpSocket:
              port: 3001
          readinessProbe:
            tcpSocket:
              port: 3001
