apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blockchain-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - custody-chain.darwin-consulting.online
      secretName: custody-chain-tls
  rules:
    - host: custody-chain.darwin-consulting.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "blockchain.fullname" . }}-frontend-service
                port:
                  number: 80
